"use strict";
const API_URL="https://ctthdtsbjjqovtmhrzzj.supabase.co/functions/v1/assistant-api";
const API_KEY_STORE="subin-assistant-api-key-v1";
const storeKey="subin-assistant-state-v4";
let TASKS={updatedAt:"",tasks:[]};
let CAL={syncedAt:"",events:[]};
let remoteReady=false;
const CAT={work:{label:"업무",emoji:"💼",cls:"work",color:"var(--work)"},dev:{label:"개발",emoji:"⚙️",cls:"dev",color:"var(--dev)"},personal:{label:"개인",emoji:"🌿",cls:"personal",color:"var(--personal)"}};
let local={filters:{work:true,dev:true,personal:true},tab:"calendar",month:"",dbMigratedV1:false};
try{const saved=JSON.parse(localStorage.getItem(storeKey)||"{}");local={...local,...saved};local.filters={work:true,dev:true,personal:true,...(local.filters||{})}}catch(e){}
const save=()=>{try{localStorage.setItem(storeKey,JSON.stringify(local));return true}catch(e){return false}};
const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
const todayISO=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Seoul',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const curMonth=()=>todayISO().slice(0,7);
const fmtMonth=ym=>{const [y,m]=ym.split("-").map(Number);return `${y}년 ${m}월`};
const fmtDate=d=>d?new Intl.DateTimeFormat("ko-KR",{timeZone:'Asia/Seoul',month:"numeric",day:"numeric",weekday:"short"}).format(new Date(d+"T12:00:00+09:00")):"날짜 미정";
const toSeoulDate=v=>v?new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Seoul',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(v)):"";
const toSeoulTime=v=>v?new Intl.DateTimeFormat('ko-KR',{timeZone:'Asia/Seoul',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date(v)).replace('24:','00:'):"";
const isDone=t=>t?.status==="done";
function consumeKeyFromHash(){const raw=location.hash.replace(/^#/,"");if(!raw)return;const params=new URLSearchParams(raw);const key=params.get('assistant-key')||params.get('key');if(key){localStorage.setItem(API_KEY_STORE,key);history.replaceState(null,"",location.pathname+location.search)}}
consumeKeyFromHash();
const getApiKey=()=>localStorage.getItem(API_KEY_STORE)||"";
function setStatus(text="",cls=""){const el=document.getElementById("sync");if(!el)return;el.textContent=text;el.className="sync"+(cls?" "+cls:"")}
function showError(msg){const el=document.getElementById('storage-status');if(el)el.textContent=msg||"";setStatus("연결 확인 필요","error")}
function clearError(){const el=document.getElementById('storage-status');if(el)el.textContent=""}
async function apiGet(resource){const key=getApiKey();if(!key)throw new Error('SETUP_REQUIRED');const r=await fetch(`${API_URL}?resource=${encodeURIComponent(resource)}`,{headers:{'x-assistant-key':key},cache:'no-store'});if(!r.ok){if(r.status===401)throw new Error('AUTH');throw new Error(`HTTP ${r.status}`)}return r.json()}
async function apiPost(body){const key=getApiKey();if(!key)throw new Error('SETUP_REQUIRED');const r=await fetch(API_URL,{method:'POST',headers:{'content-type':'application/json','x-assistant-key':key},body:JSON.stringify(body)});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||`HTTP ${r.status}`);return data}
function mapTask(r){return {id:r.external_id||r.id,dbId:r.id,title:r.title,category:r.category,due:r.due_date||"",endDate:r.end_date||"",priority:Number(r.priority)||100,urgent:!!r.urgent,status:r.status||'todo',estimateMin:r.estimate_min??null,note:r.note||"",nextAction:r.next_action||"",emoji:r.emoji||"",later:r.status==='later',completedAt:r.completed_at||"",createdAt:r.created_at||"",updatedAt:r.updated_at||""}}
function mapCalendar(r){return {id:r.external_id||r.id,title:r.title,date:toSeoulDate(r.start_at),endDate:toSeoulDate(r.end_at||r.start_at),time:r.all_day?"":toSeoulTime(r.start_at),source:'google',allDay:!!r.all_day}}
function cacheRemote(){try{localStorage.setItem('subin-assistant-remote-cache-v1',JSON.stringify({TASKS,CAL}))}catch(e){}}
function restoreCache(){try{const x=JSON.parse(localStorage.getItem('subin-assistant-remote-cache-v1')||'null');if(x?.TASKS?.tasks){TASKS=x.TASKS;CAL=x.CAL||CAL;return true}}catch(e){}return false}
async function migrateLegacyLocalState(){if(local.dbMigratedV1||!getApiKey())return;let old={};try{old=JSON.parse(localStorage.getItem(storeKey)||"{}")}catch(e){}try{const ids=new Set(TASKS.tasks.map(t=>t.id));for(const [id] of Object.entries(old.done||{}))if(ids.has(id))await apiPost({action:'complete_task',external_id:id,done:true});for(const [id,d] of Object.entries(old.dates||{}))if(ids.has(id)&&d&&typeof d.due==='string')await apiPost({action:'update_task',external_id:id,patch:{due_date:d.due||null,end_date:d.endDate||null}});for(const cat of ['work','dev','personal']){const arr=(old.order?.[cat]||[]).filter(id=>ids.has(id));if(arr.length>1)await apiPost({action:'reorder',category:cat,ordered_ids:arr})}local.dbMigratedV1=true;save()}catch(e){console.warn('legacy migration skipped',e)}}
async function refreshRemoteData(showBusy=false){if(!getApiKey()){renderSetup();return false}if(showBusy)setStatus("업데이트 중","busy");try{const [td,cd]=await Promise.all([apiGet('tasks'),apiGet('calendar')]);TASKS={updatedAt:new Date().toISOString(),tasks:(td.tasks||[]).map(mapTask)};CAL={syncedAt:new Date().toISOString(),events:(cd.events||[]).map(mapCalendar)};await migrateLegacyLocalState();if(local.dbMigratedV1){const [t2,c2]=await Promise.all([apiGet('tasks'),apiGet('calendar')]);TASKS={updatedAt:new Date().toISOString(),tasks:(t2.tasks||[]).map(mapTask)};CAL={syncedAt:new Date().toISOString(),events:(c2.events||[]).map(mapCalendar)}}remoteReady=true;cacheRemote();clearError();setStatus("최신 상태","ok");render();return true}catch(e){console.warn(e);if(e.message==='AUTH'){localStorage.removeItem(API_KEY_STORE);showError('연결 키를 다시 설정해 주세요.');renderSetup('연결 키가 맞지 않아요.');return false}if(!restoreCache()){showError('데이터를 불러오지 못했어요. 잠시 후 다시 시도해 주세요.');renderSetup('연결을 확인해 주세요.');return false}showError('지금은 저장소 연결이 불안정해서 마지막으로 불러온 내용을 보여주고 있어요.');render();return false}}
function renderSetup(message="이 기기에서 처음 한 번만 연결하면 돼요."){document.body.dataset.tab=local.tab||'calendar';document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('on',b.dataset.tab===local.tab));const app=document.getElementById('app');app.innerHTML=`<section class="card setup-card"><h2>🔐 개인 비서 연결</h2><p>${esc(message)}</p><div class="setup-row"><input id="setup-key" type="password" autocomplete="off" placeholder="연결 키"><button id="setup-save">연결</button></div></section>`;document.getElementById('setup-save').onclick=async()=>{const v=document.getElementById('setup-key').value.trim();if(!v)return;localStorage.setItem(API_KEY_STORE,v);await refreshRemoteData(true)};setStatus("연결 필요","error")}
function orderedTasks(cat,includeDone=false){return TASKS.tasks.filter(t=>t.category===cat&&(includeDone||!isDone(t))).sort((a,b)=>(a.priority||100)-(b.priority||100)||(a.createdAt||'').localeCompare(b.createdAt||'')||a.id.localeCompare(b.id))}
async function moveTask(id,dir){const t=TASKS.tasks.find(x=>x.id===id);if(!t)return;const visible=orderedTasks(t.category),i=visible.findIndex(x=>x.id===id),j=i+dir;if(i<0||j<0||j>=visible.length)return;[visible[i],visible[j]]=[visible[j],visible[i]];visible.forEach((x,n)=>x.priority=n+1);render();try{await apiPost({action:'reorder',category:t.category,ordered_ids:visible.map(x=>x.id)});setStatus("저장됨","ok");setTimeout(()=>setStatus("최신 상태","ok"),900)}catch(e){showError('순서를 저장하지 못했어요.');await refreshRemoteData(false)}}
async function toggleDone(id){const t=TASKS.tasks.find(x=>x.id===id);if(!t)return;const done=!isDone(t),prev={status:t.status,completedAt:t.completedAt};t.status=done?'done':'todo';t.completedAt=done?new Date().toISOString():'';render();try{await apiPost({action:'complete_task',external_id:id,done});setStatus("저장됨","ok");setTimeout(()=>setStatus("최신 상태","ok"),900)}catch(e){Object.assign(t,prev);showError('완료 상태를 저장하지 못했어요.');render()}}
function moveMonth(n){let [y,m]=local.month.split('-').map(Number);m+=n;while(m<1){m+=12;y--}while(m>12){m-=12;y++}local.month=`${y}-${String(m).padStart(2,'0')}`;save();render()}
function dueState(t){if(!t.due)return'none';if(t.due<todayISO())return'overdue';if(t.due===todayISO())return'today';const d=new Date(todayISO()+'T12:00:00+09:00');d.setDate(d.getDate()+1);const ti=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Seoul',year:'numeric',month:'2-digit',day:'2-digit'}).format(d);if(t.due===ti)return'tomorrow';return'future'}
function urgencyText(t){const s=dueState(t);if(s==='overdue')return'🔥 지연';if(s==='today')return'🔥 오늘 꼭';if(s==='tomorrow')return'내일';if(t.urgent)return'🔥 급함';return''}